language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly # ignore errors, see below
  - hhvm # ignore errors, see below

env:
  global:
    - SYMFONY_VERSION=""

# Heavy matrix to test every version of the bundle/package
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    # Lowest dependency
    - php: 7.1
      env: SYMFONY_VERSION="3.4.x"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.x"
    - php: 7.1
      env: SYMFONY_VERSION="4.1.x"
    - php: 7.1
      env: SYMFONY_VERSION="4.2.x"
    - php: 7.1
      env: SYMFONY_VERSION="dev-master"
  allow_failures:
    - php: hhvm
    - php: nightly
    - env: SYMFONY_VERSION="dev-master"

# Update composer, and update Symfony version depending on the matrix
before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle:$SYMFONY_VERSION; fi

# Install composer dependencies,
#  but also phpunit (to test a specific version of it)
#  and coveralls (to send the code coverage to coveralls.io, see "after_success" later in this file)
# Note: for coveralls to work you need a ".coveralls.yml" file (see other file in this gist).
install:
  - composer install

# Run script and log coverage in the "build" directory
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

# Run coveralls after success and if not in hhvm (too much cache, incorrect coverage)
after_success: |
  if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;
