language: php

php:
  - 7.1.3
  - 7.2
  - 7.3
  - nightly # allow failures

env:
  global:
    - SYMFONY_VERSION=""

matrix:
  fast_finish: true
  include:
    # Lowest dependency of php against different supported symfony versions
    - php: 7.1.3
      env: SYMFONY_VERSION="3.4.x"
    - php: 7.1.3
      env: SYMFONY_VERSION="4.0.x"
    - php: 7.1.3
      env: SYMFONY_VERSION="4.1.x"
    - php: 7.1.3
      env: SYMFONY_VERSION="4.2.x"
    - php: 7.1.3
      env: SYMFONY_VERSION="dev-master"
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION="dev-master"

# Update composer, and update Symfony version depending on the matrix
before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle:$SYMFONY_VERSION; fi

# Install composer dependencies
install:
  - composer install

# Run script and log coverage in the "build" directory
script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# Run coveralls after success
after_success: |
  php vendor/bin/coveralls -v --config .coveralls.yml
