services:

  _defaults:
    public: false
    autowire: true

  # Renderers
  forskel.renderers:
    namespace: 'siemendev\ForskelBundle\Renderer\'
    resource: '../../Renderer/*'
    tags: ['forskel.renderers']
    calls:
      - ['setTemplatePath', ['%forskel.template_root%']]

  # Twig Extension
  forskel.twig.extension:
    class: 'siemendev\ForskelBundle\Twig\ForskelExtension'
    autowire: true
    tags: ['twig.extension']

  forskel.twig.runtime:
    class: 'siemendev\ForskelBundle\Twig\ForskelRuntime'
    autowire: true
    tags: ['twig.runtime']

